### ISSUE TITLE
Your bin/console filename is too generic

### ISSUE THREAD

**Issue by MadBomber** [mooreniemi/figtree#1]
I recommend you rename the bin/console file to bin/figtree to avoid conflicts with other "console" executables.

**Comment by mooreniemi** [comment]
Thanks @MadBomber. I think in this case I will actually just remove the executables export from the gemspec, as it's not really necessary to export any for the use of the gem. Good catch.

**Comment by mooreniemi** [comment]
should be resolved by c5d26e8d917bc71f9454c8751a3dbc5fbcbf44e2 with version bump to 2.0.1
